name: flutter_codelab_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  fonts:
    - family: Staatliches
      fonts:
        - asset: assets/fonts/Staatliches-Regular.ttf
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
  
  uses-material-design: true

  assets:
    - assets/images/
